<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Company>Wyrm Software</Company>
    <Authors>WyrmUK</Authors>
    <Copyright>© $([System.DateTime]::now.Year) $(Company). All rights reserved.</Copyright>
    <Description>A TCP ModBus client for GivEnergy inverters.</Description>
    <RepositoryUrl>https://github.com/WyrmUK/Wyrm.ModBusClient.GivEnergy</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/WyrmUK/Wyrm.ModBusClient.GivEnergy</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>Nuget.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" Visible="false" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" Visible="false" PackagePath="" />
    <None Include="..\..\content\Nuget.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Wyrm.ModBusClient" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).IntegrationTests" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
